/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalaki.BadConsequence;
import napakalaki.Player;

/**
 *
 * @author juanmfajardo
 */
public class PendingBadConsequenceView extends javax.swing.JPanel {

    private Player pendingBadConsequenceModel; 
    /**
     * Creates new form PendingBadConsequenceView
     */
    public PendingBadConsequenceView() {
        initComponents();
    }

    public void setPendingBadConsequence(Player p){
        
        pendingBadConsequenceModel = p;
        
        LabelPendingBadConsequence.setText(pendingBadConsequenceModel.getPendingBadConsequence().toString());
        
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelPendingBadConsequence = new javax.swing.JLabel();

        LabelPendingBadConsequence.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelPendingBadConsequence.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LabelPendingBadConsequence)
                .addGap(0, 96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelPendingBadConsequence)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelPendingBadConsequence;
    // End of variables declaration//GEN-END:variables
}
