/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;
import napakalaki.Napakalaki;
import napakalaki.Player;
import napakalaki.Treasure;

/**
 *
 * @author juanmfajardo
 */
public class PlayerView extends javax.swing.JPanel {
    private Player playerModel;
    private Napakalaki napakalakiModel;
    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
        initComponents();
    }
    
    public void setNapakalaki(Napakalaki n){
        napakalakiModel = n;
    }
    
    public void setPlayer(Player unPlayer){
        playerModel = unPlayer;
        
        LabelName.setText(playerModel.getName());
        LabelLevel.setText(Integer.toString(playerModel.getLevels()));
        LabelDead.setText(Boolean.toString(playerModel.isDead()));
        LabelCanISteal.setText(Boolean.toString(playerModel.canISteal()));
        
        LabelEnemy.setText(playerModel.getEnemy().getName());
        
        LabelPendingBadConsequence.setText(playerModel.getPendingBadConsequence().toString());
        boolean es;
        if(playerModel.getClass().getName().equalsIgnoreCase("napakalaki.player") ){
            es = false;
        }
        else{
            es = true;
        }
        LabelSectario.setText(Boolean.toString(es) );
        
        this.fillTreasurePanel(hiddenTreasures, playerModel.getHiddenTreasures());
        this.fillTreasurePanel(visibleTreasures, playerModel.getVisibleTreasures());
        
        repaint();
        revalidate();
    }

    private void fillTreasurePanel (JPanel aPanel, ArrayList<Treasure> aList){
        //Se elimina la información antigua, si la hubiera
        aPanel.removeAll();
        //Se recorre la lista de tesoros construyendo y añadiendo sus vistas al panel
        for (Treasure t: aList){
            TreasureView aTreasureView = new TreasureView();
            aTreasureView.setTreasure(t);
            aTreasureView.setVisible(true);
            aPanel.add(aTreasureView);
        }
        
        //Se fuerza la actualización visual del panel
        aPanel.repaint();
        aPanel.revalidate();
    }
    
    private ArrayList<Treasure> getSelectedTreasures(JPanel aPanel) {
// Se recorren los tesoros que contiene el panel,
//    almacenando en un vector aquellos que están seleccionados.
//    Finalmente se devuelve dicho vector.

        TreasureView tv;
        ArrayList<Treasure> output = new ArrayList();
        for (Component c : aPanel.getComponents()) {
            tv = (TreasureView) c;
            if (tv.isSelected()) {
                output.add(tv.getTreasure());
            }
        }
        return output;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelName = new javax.swing.JLabel();
        LabelLevel = new javax.swing.JLabel();
        LabelDead = new javax.swing.JLabel();
        LabelCanISteal = new javax.swing.JLabel();
        LabelEnemy = new javax.swing.JLabel();
        LabelPendingBadConsequence = new javax.swing.JLabel();
        LabelSectario = new javax.swing.JLabel();
        hiddenTreasures = new javax.swing.JPanel();
        visibleTreasures = new javax.swing.JPanel();
        ButtonStealTreasure = new javax.swing.JButton();
        ButtonMakeVisible = new javax.swing.JButton();
        ButtonDiscardTreasures = new javax.swing.JButton();
        ButtonDiscardAllTreasures = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        LabelName.setText("Name");

        LabelLevel.setText("Level");

        LabelDead.setText("Dead");

        LabelCanISteal.setText("CanISteal");

        LabelEnemy.setText("Enemy");

        LabelPendingBadConsequence.setText("PendingBadConsequence");

        LabelSectario.setText("Sectario");

        hiddenTreasures.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102)));

        visibleTreasures.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102)));

        ButtonStealTreasure.setText("Steal Treasure");
        ButtonStealTreasure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStealTreasureActionPerformed(evt);
            }
        });

        ButtonMakeVisible.setText("Make Visible");
        ButtonMakeVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMakeVisibleActionPerformed(evt);
            }
        });

        ButtonDiscardTreasures.setText("Discard Treasures");
        ButtonDiscardTreasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDiscardTreasuresActionPerformed(evt);
            }
        });

        ButtonDiscardAllTreasures.setText("Discard All Treasures");
        ButtonDiscardAllTreasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDiscardAllTreasuresActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Nivel: ");

        jLabel3.setText("Muerto: ");

        jLabel4.setText("Puede Robar: ");

        jLabel5.setText("Enemigo: ");

        jLabel6.setText("Mal rollo pendiente: ");

        jLabel7.setText("Sectario: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(visibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 128, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelLevel))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LabelDead))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LabelCanISteal)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelEnemy))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelSectario))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelPendingBadConsequence)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonDiscardTreasures)
                            .addComponent(ButtonMakeVisible)
                            .addComponent(ButtonStealTreasure)
                            .addComponent(ButtonDiscardAllTreasures))
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelLevel)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelName)
                                    .addComponent(jLabel1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelDead)
                            .addComponent(jLabel3))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCanISteal)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelEnemy)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelPendingBadConsequence)
                            .addComponent(jLabel6))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelSectario)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonStealTreasure)
                        .addGap(20, 20, 20)
                        .addComponent(ButtonMakeVisible)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonDiscardTreasures)
                        .addGap(27, 27, 27)
                        .addComponent(ButtonDiscardAllTreasures)))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(visibleTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(hiddenTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonMakeVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMakeVisibleActionPerformed
        // TODO add your handling code here:
        ArrayList<Treasure> selHidden = getSelectedTreasures(hiddenTreasures);
        napakalakiModel.makeTreasuresVisible(selHidden);
        setPlayer(napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_ButtonMakeVisibleActionPerformed

    private void ButtonDiscardTreasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDiscardTreasuresActionPerformed
        // TODO add your handling code here:
        ArrayList<Treasure> selHidden = getSelectedTreasures(hiddenTreasures);
        ArrayList<Treasure> selVisible = getSelectedTreasures(visibleTreasures);
        
        for(Treasure t : selHidden){
            playerModel.discardHiddenTreasure(t);
        }
        
        for(Treasure t : selVisible){
            playerModel.discardVisibleTrasure(t);
        }
        
        setPlayer(napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_ButtonDiscardTreasuresActionPerformed

    private void ButtonDiscardAllTreasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDiscardAllTreasuresActionPerformed
        // TODO add your handling code here:
        playerModel.discardAllTreasures();
        setPlayer(napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_ButtonDiscardAllTreasuresActionPerformed

    private void ButtonStealTreasureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStealTreasureActionPerformed
        // TODO add your handling code here:
        if(playerModel.stealTreasure() != null){
            ButtonStealTreasure.setVisible(false);
        }
        setPlayer(napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_ButtonStealTreasureActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDiscardAllTreasures;
    private javax.swing.JButton ButtonDiscardTreasures;
    private javax.swing.JButton ButtonMakeVisible;
    private javax.swing.JButton ButtonStealTreasure;
    private javax.swing.JLabel LabelCanISteal;
    private javax.swing.JLabel LabelDead;
    private javax.swing.JLabel LabelEnemy;
    private javax.swing.JLabel LabelLevel;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelPendingBadConsequence;
    private javax.swing.JLabel LabelSectario;
    private javax.swing.JPanel hiddenTreasures;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel visibleTreasures;
    // End of variables declaration//GEN-END:variables
}
